apiVersion: batch/v1
kind: Job
metadata:
  name: port-scan-job
spec:
  completions: 10
  parallelism: 10
  template:
    metadata:
      name: port-scan
    spec:
      containers:
        - name: port-scan-c
          image: 192.168.75.130:5000/port-scan-ns
      restartPolicy: OnFailure
